set "installPath=%SUBNAUTICA_PATH%"
set "buildPath=..\..\BuildTarget"
set "avsPath=%AVS_PATH%"

rmdir /Q /S "%installPath%\BepInEx\plugins\Archon"
mkdir "%installPath%\BepInEx\plugins\Archon"
mkdir "%installPath%\BepInEx\plugins\Archon\Sprites"
mkdir "%installPath%\BepInEx\plugins\Archon\EngineSounds"
mkdir "%installPath%\BepInEx\plugins\Archon\AutoPilotVoices"
mkdir "%installPath%\BepInEx\plugins\Archon\AutoPilotVoices\ShirubaFoxy"
mkdir "%installPath%\BepInEx\plugins\Archon\EngineSounds\ShirubaFoxy"

copy /Y "%buildPath%\Subnautica Archon_Data\Managed\ArchonScripts.dll" "%installPath%\BepInEx\plugins\Archon"
copy /Y "..\ArchonUnity\Assets\AssetBundles\Windows\archon" "%installPath%\BepInEx\plugins\Archon"
copy /Y "..\ArchonUnity\Assets\AssetBundles\OSX\archon" "%installPath%\BepInEx\plugins\Archon\archon.osx"
copy /Y "..\ArchonPlugin\bin\Release\net4.7.2\Subnautica Archon.dll" "%installPath%\BepInEx\plugins\Archon"
mkdir "%installPath%\BepInEx\plugins\Archon\images"
copy /Y "..\images\*.*" "%installPath%\BepInEx\plugins\Archon\images"
mkdir "%installPath%\BepInEx\plugins\Archon\Localization"
copy /Y "..\Localization\*.*" "%installPath%\BepInEx\plugins\Archon\Localization"
copy /Y "%avsPath%\AVS\Localization\*.*" "%installPath%\BepInEx\plugins\Archon\Localization"
copy /Y "%avsPath%\AVS\bin\Release\net4.7.2\AVS.dll" "%installPath%\BepInEx\plugins\Archon"
copy /Y "%avsPath%\AVS\bin\Release\net4.7.2\Assembly-CSharp_publicized.dll" "%installPath%\BepInEx\plugins\Archon"
copy /Y "%avsPath%\Deploy\*.*" "%installPath%\BepInEx\plugins\Archon"
copy /Y "%avsPath%\Deploy\Sprites\*.*" "%installPath%\BepInEx\plugins\Archon\Sprites"
copy /Y "%avsPath%\Deploy\EngineSounds\*.*" "%installPath%\BepInEx\plugins\Archon\EngineSounds"
copy /Y "%avsPath%\Deploy\EngineSounds\ShirubaFoxy\*.*" "%installPath%\BepInEx\plugins\Archon\EngineSounds\ShirubaFoxy"
copy /Y "%avsPath%\Deploy\AutoPilotVoices\*.*" "%installPath%\BepInEx\plugins\Archon\AutoPilotVoices"
copy /Y "%avsPath%\Deploy\AutoPilotVoices\ShirubaFoxy\*.*" "%installPath%\BepInEx\plugins\Archon\AutoPilotVoices\ShirubaFoxy"

rem "%installPath%\Subnautica.exe"